name: Lint Code Base

on:
  pull_request:
    branches:
      - main  # или ветка, на которую делаются пулл-реквесты
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.jsx'
      - '.eslintrc.js'
      - 'tsconfig.json'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # укажи нужную версию Node.js

    - name: Install dependencies
      run: yarn install  # или npm install, если используешь npm

    - name: Run ESLint
      run: yarn lint  # или npx eslint . если используешь npx для запуска eslint
